#!/usr/bin/env fish
# dots/generate-monitors.fish — auto-generate ~/.config/hypr/monitors.conf
# from the monitors Hyprland actually detects on THIS machine, instead of
# reusing a hardcoded config copied from a different laptop.
#
# Usage: fish generate-monitors.fish [--dry-run]
#   Run this any time your monitor setup changes (new laptop, new external
#   display, etc). Monitors are laid out left-to-right in detection order at
#   their preferred resolution/refresh rate and current scale.
#
# Note: this only works while Hyprland is running (it reads `hyprctl monitors`).

set -l GREEN  (set_color green)
set -l YELLOW (set_color yellow)
set -l RED    (set_color red)
set -l RESET  (set_color normal)

set -l DRY_RUN false
if contains -- --dry-run $argv
    set DRY_RUN true
end

if not command -q hyprctl
    echo $RED"[error]"$RESET" hyprctl not found — this must be run inside a Hyprland session."
    exit 1
end

set -l monitors_json (hyprctl monitors -j)
set -l count (echo $monitors_json | jq 'length')

if test $count -eq 0
    echo $RED"[error]"$RESET" hyprctl reported 0 monitors — nothing to generate."
    exit 1
end

set -l out $HOME/.config/hypr/monitors.conf
set -l tmp (mktemp)

echo "# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
#
# Auto-generated by dots/generate-monitors.fish for this machine's detected
# hardware. Re-run that script if your monitor setup changes. Feel free to
# tweak positions below (e.g. to place an external monitor above/below/beside
# the laptop screen) — this file won't be overwritten unless you re-run it.

env = GDK_SCALE,1
" > $tmp

set -l x_offset 0
for i in (seq 0 (math $count - 1))
    set -l name (echo $monitors_json | jq -r ".[$i].name")
    set -l width (echo $monitors_json | jq -r ".[$i].width")
    set -l height (echo $monitors_json | jq -r ".[$i].height")
    set -l refresh (echo $monitors_json | jq -r ".[$i].refreshRate" | xargs printf "%.2f")
    set -l scale (echo $monitors_json | jq -r ".[$i].scale")
    set -l is_laptop (echo $monitors_json | jq -r ".[$i].name" | string match -qr '^eDP' && echo true || echo false)

    if test $is_laptop = true
        echo "# Laptop screen" >> $tmp
    else
        echo "# External monitor" >> $tmp
    end
    echo "monitor = $name, $width""x""$height@$refresh, $x_offset""x""0, $scale" >> $tmp

    set x_offset (math $x_offset + $width)
end

if test $DRY_RUN = true
    echo $YELLOW"[dry-run]"$RESET" Would write $out:"
    cat $tmp
    rm $tmp
    exit 0
end

mkdir -p (dirname $out)
mv $tmp $out

echo $GREEN"[info]"$RESET"  Generated $out for $count monitor(s):"
cat $out
